import { cn } from "~/utils/cn";

import type { IconProps } from "./types";

export function GaugeIcon({ className, ...props }: IconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="20"
      height="20"
      viewBox="0 0 20 20"
      className={cn("size-[1em]", className)}
      {...props}
    >
      <g fill="currentColor">
        <circle
          cx="10"
          cy="11"
          r="1"
          fill="currentColor"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
        ></circle>
        <line
          x1="10"
          y1="11"
          x2="5"
          y2="6"
          fill="none"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
        ></line>
        <line
          x1="10"
          y1="4"
          x2="10"
          y2="6"
          fill="none"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
        ></line>
        <line
          x1="14.95"
          y1="6.05"
          x2="13.536"
          y2="7.464"
          fill="none"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
        ></line>
        <line
          x1="17"
          y1="11"
          x2="15"
          y2="11"
          fill="none"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
        ></line>
        <line
          x1="14.95"
          y1="15.95"
          x2="13.536"
          y2="14.536"
          fill="none"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
        ></line>
        <line
          x1="5.05"
          y1="15.95"
          x2="6.464"
          y2="14.536"
          fill="none"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
        ></line>
        <line
          x1="3"
          y1="11"
          x2="5"
          y2="11"
          fill="none"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
        ></line>
        <path
          d="m14.95,15.95c1.267-1.267,2.05-3.017,2.05-4.95,0-3.866-3.134-7-7-7-.626,0-1.229.09-1.806.244"
          fill="none"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
        ></path>
        <path
          d="m3.244,9.194c-.154.577-.244,1.181-.244,1.806,0,1.933.784,3.683,2.05,4.95"
          fill="none"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
        ></path>
      </g>
    </svg>
  );
}
