/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './app/__root'
import { Route as protectedprotectedDotlayoutRouteImport } from './app/(protected)/(protected).layout'
import { Route as indexIndexDotpageRouteImport } from './app/index/index.page'
import { Route as postPostIdPostIdDotpageRouteImport } from './app/post/$postId/$postId.page'
import { Route as protectedProtectedDotpageRouteImport } from './app/(protected)/protected.page'
import { Route as postPostDotpageRouteImport } from './app/post/post.page'
import { ServerRoute as apiAuthSplatServerRouteImport } from './app/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const protectedprotectedDotlayoutRoute =
  protectedprotectedDotlayoutRouteImport.update({
    id: '/_(protected).layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const indexIndexDotpageRoute = indexIndexDotpageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const postPostIdPostIdDotpageRoute = postPostIdPostIdDotpageRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedProtectedDotpageRoute =
  protectedProtectedDotpageRouteImport.update({
    id: '/protected',
    path: '/protected',
    getParentRoute: () => protectedprotectedDotlayoutRoute,
  } as any)
const postPostDotpageRoute = postPostDotpageRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => rootRouteImport,
} as any)
const apiAuthSplatServerRoute = apiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexIndexDotpageRoute
  '/post': typeof postPostDotpageRoute
  '/protected': typeof protectedProtectedDotpageRoute
  '/post/$postId': typeof postPostIdPostIdDotpageRoute
}
export interface FileRoutesByTo {
  '/': typeof indexIndexDotpageRoute
  '/post': typeof postPostDotpageRoute
  '/protected': typeof protectedProtectedDotpageRoute
  '/post/$postId': typeof postPostIdPostIdDotpageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexIndexDotpageRoute
  '/_(protected).layout': typeof protectedprotectedDotlayoutRouteWithChildren
  '/post/': typeof postPostDotpageRoute
  '/_(protected).layout/protected': typeof protectedProtectedDotpageRoute
  '/post/$postId': typeof postPostIdPostIdDotpageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/post' | '/protected' | '/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/post' | '/protected' | '/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/_(protected).layout'
    | '/post/'
    | '/_(protected).layout/protected'
    | '/post/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexIndexDotpageRoute: typeof indexIndexDotpageRoute
  protectedprotectedDotlayoutRoute: typeof protectedprotectedDotlayoutRouteWithChildren
  postPostDotpageRoute: typeof postPostDotpageRoute
  postPostIdPostIdDotpageRoute: typeof postPostIdPostIdDotpageRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof apiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof apiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof apiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  apiAuthSplatServerRoute: typeof apiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_(protected).layout': {
      id: '/_(protected).layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedprotectedDotlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexIndexDotpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof postPostIdPostIdDotpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(protected).layout/protected': {
      id: '/_(protected).layout/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof protectedProtectedDotpageRouteImport
      parentRoute: typeof protectedprotectedDotlayoutRoute
    }
    '/post/': {
      id: '/post/'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof postPostDotpageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof apiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface protectedprotectedDotlayoutRouteChildren {
  protectedProtectedDotpageRoute: typeof protectedProtectedDotpageRoute
}

const protectedprotectedDotlayoutRouteChildren: protectedprotectedDotlayoutRouteChildren =
  {
    protectedProtectedDotpageRoute: protectedProtectedDotpageRoute,
  }

const protectedprotectedDotlayoutRouteWithChildren =
  protectedprotectedDotlayoutRoute._addFileChildren(
    protectedprotectedDotlayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  indexIndexDotpageRoute: indexIndexDotpageRoute,
  protectedprotectedDotlayoutRoute:
    protectedprotectedDotlayoutRouteWithChildren,
  postPostDotpageRoute: postPostDotpageRoute,
  postPostIdPostIdDotpageRoute: postPostIdPostIdDotpageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  apiAuthSplatServerRoute: apiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
